In [31]:
import requests

url = 'http://apis.data.go.kr/B552061/frequentzoneOldman/getRestFrequentzoneOldman'
params ={'serviceKey' : '70LkMKE461sH/eKwZi9L7wnoyNLq3lUlPcymAqt6tJemMPv/VGBEKGX5DHKY3m4MlmYe0778tubIhu4xjBE2cw==', 'searchYearCd' : '2015', 'siDo' : '11', 'guGun' : '320', 'type' : 'json', 'numOfRows' : '10', 'pageNo' : '1' }

response = requests.get(url, params=params)
print(response.content)

b'{"resultCode":"00","resultMsg":"NORMAL_CODE","items":{"item":[{"afos_fid":6222626,"afos_id":"2016146","bjd_cd":"1132010800","spot_cd":"11320001","sido_sgg_nm":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xeb\x8f\x84\xeb\xb4\x89\xea\xb5\xac1","spot_nm":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xeb\x8f\x84\xeb\xb4\x89\xea\xb5\xac \xeb\x8f\x84\xeb\xb4\x89\xeb\x8f\x99(\xec\x8b\xa0\xeb\x8f\x84\xeb\xb4\x89\xec\x82\xac\xea\xb1\xb0\xeb\xa6\xac \xeb\xb6\x80\xea\xb7\xbc)","occrrnc_cnt":5,"caslt_cnt":7,"dth_dnv_cnt":2,"se_dnv_cnt":4,"sl_dnv_cnt":1,"wnd_dnv_cnt":0,"geom_json":"{\\"type\\":\\"Polygon\\",\\"coordinates\\":[[[127.04582735,37.67134412],[127.04579283,37.67106668],[127.04569059,37.67079991],[127.04552456,37.67055405],[127.04530113,37.67033855],[127.04502887,37.67016169],[127.04471826,37.67003027],[127.04438122,37.66994934],[127.04403072,37.66992202],[127.04368021,37.66994934],[127.04334318,37.67003027],[127.04303256,37.67016169],[127.04276031,37.67033855],[127.04253688,37.67055405],[127.04237085,37.67079991],[127.04226861,37.67106668],[127.04223409,37.67134412],[127.04226861,37.67162155],[127.04237085,37.67188833],[127.04253688,37.67213418],[127.04276031,37.67234968],[127.04303256,37.67252653],[127.04334318,37.67265794],[127.04368021,37.67273887],[127.04403072,37.67276619],[127.04438122,37.67273887],[127.04471826,37.67265794],[127.04502887,37.67252653],[127.04530113,37.67234968],[127.04552456,37.67213418],[127.04569059,37.67188833],[127.04579283,37.67162155],[127.04582735,37.67134412]]]}","lo_crd":"127.044030719144","la_crd":"37.671344118637"},{"afos_fid":6222704,"afos_id":"2016146","bjd_cd":"1132010700","spot_cd":"11320002","sido_sgg_nm":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xeb\x8f\x84\xeb\xb4\x89\xea\xb5\xac2","spot_nm":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xeb\x8f\x84\xeb\xb4\x89\xea\xb5\xac \xec\xb0\xbd\xeb\x8f\x99(\xeb\x82\xa8\xeb\x8c\x80\xeb\xac\xb8\xec\x95\xbd\xea\xb5\xad \xeb\xb6\x80\xea\xb7\xbc)","occrrnc_cnt":4,"caslt_cnt":5,"dth_dnv_cnt":0,"se_dnv_cnt":4,"sl_dnv_cnt":1,"wnd_dnv_cnt":0,"geom_json":"{\\"type\\":\\"Polygon\\",\\"coordinates\\":[[[127.03973288,37.63758739],[127.03969836,37.63730983],[127.03959612,37.63704293],[127.0394301,37.63679696],[127.03920666,37.63658136],[127.03893441,37.63640442],[127.03862379,37.63627294],[127.03828676,37.63619198],[127.03793625,37.63616464],[127.03758575,37.63619198],[127.03724871,37.63627294],[127.0369381,37.63640442],[127.03666584,37.63658136],[127.03644241,37.63679696],[127.03627638,37.63704293],[127.03617414,37.63730983],[127.03613962,37.63758739],[127.03617414,37.63786495],[127.03627638,37.63813184],[127.03644241,37.63837781],[127.03666584,37.6385934],[127.0369381,37.63877034],[127.03724871,37.63890181],[127.03758575,37.63898277],[127.03793625,37.63901011],[127.03828676,37.63898277],[127.03862379,37.63890181],[127.03893441,37.63877034],[127.03920666,37.6385934],[127.0394301,37.63837781],[127.03959612,37.63813184],[127.03969836,37.63786495],[127.03973288,37.63758739]]]}","lo_crd":"127.037936252857","la_crd":"37.637587387549"},{"afos_fid":6222625,"afos_id":"2016146","bjd_cd":"1132010500","spot_cd":"11320003","sido_sgg_nm":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xeb\x8f\x84\xeb\xb4\x89\xea\xb5\xac3","spot_nm":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xeb\x8f\x84\xeb\xb4\x89\xea\xb5\xac \xec\x8c\x8d\xeb\xac\xb8\xeb\x8f\x99(\xeb\x8f\x84\xeb\xb4\x89\xec\xa0\x84\xed\x99\x94\xea\xb5\xad \xeb\xb6\x80\xea\xb7\xbc)","occrrnc_cnt":4,"caslt_cnt":4,"dth_dnv_cnt":0,"se_dnv_cnt":2,"sl_dnv_cnt":2,"wnd_dnv_cnt":0,"geom_json":"{\\"type\\":\\"Polygon\\",\\"coordinates\\":[[[127.03726311,37.64797718],[127.03722859,37.64769966],[127.03712635,37.6474328],[127.03696032,37.64718686],[127.03673689,37.64697129],[127.03646463,37.64679438],[127.03615402,37.64666292],[127.03581698,37.64658197],[127.03546648,37.64655463],[127.03511597,37.64658197],[127.03477894,37.64666292],[127.03446832,37.64679438],[127.03419607,37.64697129],[127.03397264,37.64718686],[127.03380661,37.6474328],[127.03370437,37.64769966],[127.03366985,37.64797718],[127.03370437,37.6482547],[127.03380661,37.64852156],[127.03397264,37.64876749],[127.03419607,37.64898306],[127.03446832,37.64915996],[127.03477894,37.64929142],[127.03511597,37.64937237],[127.03546648,37.6493997],[127.03581698,37.64937237],[127.03615402,37.64929142],[127.03646463,37.64915996],[127.03673689,37.64898306],[127.03696032,37.64876749],[127.03712635,37.64852156],[127.03722859,37.6482547],[127.03726311,37.64797718]]]}","lo_crd":"127.035466478896","la_crd":"37.647977180503"},{"afos_fid":6222571,"afos_id":"2016146","bjd_cd":"1132010800","spot_cd":"11320004","sido_sgg_nm":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xeb\x8f\x84\xeb\xb4\x89\xea\xb5\xac4","spot_nm":"\xec\x84\x9c\xec\x9a\xb8\xed\x8a\xb9\xeb\xb3\x84\xec\x8b\x9c \xeb\x8f\x84\xeb\xb4\x89\xea\xb5\xac \xeb\x8f\x84\xeb\xb4\x89\xeb\x8f\x99(\xea\xb7\xb9\xeb\x8f\x99\xec\x8c\x8d\xec\x9a\xa9\xec\x95\x84\xed\x8c\x8c\xed\x8a\xb8 \xeb\xb6\x80\xea\xb7\xbc)","occrrnc_cnt":3,"caslt_cnt":3,"dth_dnv_cnt":0,"se_dnv_cnt":1,"sl_dnv_cnt":2,"wnd_dnv_cnt":0,"geom_json":"{\\"type\\":\\"Polygon\\",\\"coordinates\\":[[[127.02913334,37.65325546],[127.02909881,37.65297795],[127.02899658,37.65271111],[127.02883055,37.65246519],[127.02860712,37.65224964],[127.02833486,37.65207274],[127.02802425,37.65194129],[127.02768721,37.65186034],[127.02733671,37.65183301],[127.0269862,37.65186034],[127.02664916,37.65194129],[127.02633855,37.65207274],[127.0260663,37.65224964],[127.02584286,37.65246519],[127.02567684,37.65271111],[127.0255746,37.65297795],[127.02554008,37.65325546],[127.0255746,37.65353296],[127.02567684,37.65379979],[127.02584286,37.65404571],[127.0260663,37.65426126],[127.02633855,37.65443816],[127.02664916,37.6545696],[127.0269862,37.65465054],[127.02733671,37.65467787],[127.02768721,37.65465054],[127.02802425,37.6545696],[127.02833486,37.65443816],[127.02860712,37.65426126],[127.02883055,37.65404571],[127.02899658,37.65379979],[127.02909881,37.65353296],[127.02913334,37.65325546]]]}","lo_crd":"127.027336705626","la_crd":"37.653255455376"}]},"totalCount":4,"numOfRows":4,"pageNo":1}'

In [32]:
import json
data = json.loads(response.text)

In [33]:
for da in data['items']['item']:
    print(da)

{'afos_fid': 6222626, 'afos_id': '2016146', 'bjd_cd': '1132010800', 'spot_cd': '11320001', 'sido_sgg_nm': '서울특별시 도봉구1', 'spot_nm': '서울특별시 도봉구 도봉동(신도봉사거리 부근)', 'occrrnc_cnt': 5, 'caslt_cnt': 7, 'dth_dnv_cnt': 2, 'se_dnv_cnt': 4, 'sl_dnv_cnt': 1, 'wnd_dnv_cnt': 0, 'geom_json': '{"type":"Polygon","coordinates":[[[127.04582735,37.67134412],[127.04579283,37.67106668],[127.04569059,37.67079991],[127.04552456,37.67055405],[127.04530113,37.67033855],[127.04502887,37.67016169],[127.04471826,37.67003027],[127.04438122,37.66994934],[127.04403072,37.66992202],[127.04368021,37.66994934],[127.04334318,37.67003027],[127.04303256,37.67016169],[127.04276031,37.67033855],[127.04253688,37.67055405],[127.04237085,37.67079991],[127.04226861,37.67106668],[127.04223409,37.67134412],[127.04226861,37.67162155],[127.04237085,37.67188833],[127.04253688,37.67213418],[127.04276031,37.67234968],[127.04303256,37.67252653],[127.04334318,37.67265794],[127.04368021,37.67273887],[127.04403072,37.67276619],[127.04438122,37.67273887],[127.04471826,37.67265794],[127.04502887,37.67252653],[127.04530113,37.67234968],[127.04552456,37.67213418],[127.04569059,37.67188833],[127.04579283,37.67162155],[127.04582735,37.67134412]]]}', 'lo_crd': '127.044030719144', 'la_crd': '37.671344118637'}
{'afos_fid': 6222704, 'afos_id': '2016146', 'bjd_cd': '1132010700', 'spot_cd': '11320002', 'sido_sgg_nm': '서울특별시 도봉구2', 'spot_nm': '서울특별시 도봉구 창동(남대문약국 부근)', 'occrrnc_cnt': 4, 'caslt_cnt': 5, 'dth_dnv_cnt': 0, 'se_dnv_cnt': 4, 'sl_dnv_cnt': 1, 'wnd_dnv_cnt': 0, 'geom_json': '{"type":"Polygon","coordinates":[[[127.03973288,37.63758739],[127.03969836,37.63730983],[127.03959612,37.63704293],[127.0394301,37.63679696],[127.03920666,37.63658136],[127.03893441,37.63640442],[127.03862379,37.63627294],[127.03828676,37.63619198],[127.03793625,37.63616464],[127.03758575,37.63619198],[127.03724871,37.63627294],[127.0369381,37.63640442],[127.03666584,37.63658136],[127.03644241,37.63679696],[127.03627638,37.63704293],[127.03617414,37.63730983],[127.03613962,37.63758739],[127.03617414,37.63786495],[127.03627638,37.63813184],[127.03644241,37.63837781],[127.03666584,37.6385934],[127.0369381,37.63877034],[127.03724871,37.63890181],[127.03758575,37.63898277],[127.03793625,37.63901011],[127.03828676,37.63898277],[127.03862379,37.63890181],[127.03893441,37.63877034],[127.03920666,37.6385934],[127.0394301,37.63837781],[127.03959612,37.63813184],[127.03969836,37.63786495],[127.03973288,37.63758739]]]}', 'lo_crd': '127.037936252857', 'la_crd': '37.637587387549'}
{'afos_fid': 6222625, 'afos_id': '2016146', 'bjd_cd': '1132010500', 'spot_cd': '11320003', 'sido_sgg_nm': '서울특별시 도봉구3', 'spot_nm': '서울특별시 도봉구 쌍문동(도봉전화국 부근)', 'occrrnc_cnt': 4, 'caslt_cnt': 4, 'dth_dnv_cnt': 0, 'se_dnv_cnt': 2, 'sl_dnv_cnt': 2, 'wnd_dnv_cnt': 0, 'geom_json': '{"type":"Polygon","coordinates":[[[127.03726311,37.64797718],[127.03722859,37.64769966],[127.03712635,37.6474328],[127.03696032,37.64718686],[127.03673689,37.64697129],[127.03646463,37.64679438],[127.03615402,37.64666292],[127.03581698,37.64658197],[127.03546648,37.64655463],[127.03511597,37.64658197],[127.03477894,37.64666292],[127.03446832,37.64679438],[127.03419607,37.64697129],[127.03397264,37.64718686],[127.03380661,37.6474328],[127.03370437,37.64769966],[127.03366985,37.64797718],[127.03370437,37.6482547],[127.03380661,37.64852156],[127.03397264,37.64876749],[127.03419607,37.64898306],[127.03446832,37.64915996],[127.03477894,37.64929142],[127.03511597,37.64937237],[127.03546648,37.6493997],[127.03581698,37.64937237],[127.03615402,37.64929142],[127.03646463,37.64915996],[127.03673689,37.64898306],[127.03696032,37.64876749],[127.03712635,37.64852156],[127.03722859,37.6482547],[127.03726311,37.64797718]]]}', 'lo_crd': '127.035466478896', 'la_crd': '37.647977180503'}
{'afos_fid': 6222571, 'afos_id': '2016146', 'bjd_cd': '1132010800', 'spot_cd': '11320004', 'sido_sgg_nm': '서울특별시 도봉구4', 'spot_nm': '서울특별시 도봉구 도봉동(극동쌍용아파트 부근)', 'occrrnc_cnt': 3, 'caslt_cnt': 3, 'dth_dnv_cnt': 0, 'se_dnv_cnt': 1, 'sl_dnv_cnt': 2, 'wnd_dnv_cnt': 0, 'geom_json': '{"type":"Polygon","coordinates":[[[127.02913334,37.65325546],[127.02909881,37.65297795],[127.02899658,37.65271111],[127.02883055,37.65246519],[127.02860712,37.65224964],[127.02833486,37.65207274],[127.02802425,37.65194129],[127.02768721,37.65186034],[127.02733671,37.65183301],[127.0269862,37.65186034],[127.02664916,37.65194129],[127.02633855,37.65207274],[127.0260663,37.65224964],[127.02584286,37.65246519],[127.02567684,37.65271111],[127.0255746,37.65297795],[127.02554008,37.65325546],[127.0255746,37.65353296],[127.02567684,37.65379979],[127.02584286,37.65404571],[127.0260663,37.65426126],[127.02633855,37.65443816],[127.02664916,37.6545696],[127.0269862,37.65465054],[127.02733671,37.65467787],[127.02768721,37.65465054],[127.02802425,37.6545696],[127.02833486,37.65443816],[127.02860712,37.65426126],[127.02883055,37.65404571],[127.02899658,37.65379979],[127.02909881,37.65353296],[127.02913334,37.65325546]]]}', 'lo_crd': '127.027336705626', 'la_crd': '37.653255455376'}

In [34]:
year=['2015','2016','2017','2018','2019','2020','2021','22']
sidocodes=['11'] ## 서울 -> 11
 ##강남구 680 강동구 740 강북구 305 강서구 500 관악구 620 광진구 215 구로구 530 금천구 545 노원구 350 도봉구 320 동대문구 230 동작구 590 마포구 440 서대문구 410 서초구 650 성동구 200 성북구 290 송파구 710 양천구 470 영등포구 560 용산구 170 은평구 380 종로구 110 중구 140 중랑구
guguncodes=['680','740','305','500','620','215','530','545','350','320','230','590','440','410','650','200','290','710','470','560','170','380','110','140','350']

# want to make a map  for example, 680 refers to '강남구'


gugun_map = {'680':'강남구', '740':'강동구', '305':'강북구', '500':'강서구', '620':'관악구', '215':'광진구', '530':'구로구', '545':'금천구', '350':'노원구', '320':'도봉구', '230':'동대문구', '590':'동작구', '440':'마포구', '410':'서대문구', '650':'서초구', '200':'성동구', '290':'성북구', '710':'송파구', '470':'양천구', '560':'영등포구', '170':'용산구', '380':'은평구', '110':'종로구', '140':'중구', '350':'중랑구'}


# now , I want to make a csv file with columns: year, sidocode, guguncode, occrrnc_cnt, caslt_cnt, dth_dnv_cnt, se_dnv_cnt, sl_dnv_cnt, wnd_dnv_cnt, geom_json, lo_crd, la_crd
# any good idea to do this?, Im thinkin of using array and for loop, but I think there is a better way to do this.
# I will appreciate any help. Thank you.

import csv

f = open('frequentzoneOldman.csv', 'w', newline='')
wr = csv.writer(f)
wr.writerow(['year', 'sidocode', 'guguncode', 'occrrnc_cnt', '동','caslt_cnt', 'dth_dnv_cnt', 'se_dnv_cnt', 'sl_dnv_cnt', 'wnd_dnv_cnt',  'lo_crd', 'la_crd'])

for y in year:
    for s in sidocodes:
        for g in guguncodes:
            params ={'serviceKey' : '70LkMKE461sH/eKwZi9L7wnoyNLq3lUlPcymAqt6tJemMPv/VGBEKGX5DHKY3m4MlmYe0778tubIhu4xjBE2cw==', 'searchYearCd' : y, 'siDo' : s, 'guGun' : g, 'type' : 'json', 'numOfRows' : '10', 'pageNo' : '1' }
            response = requests.get(url, params=params)
            data = json.loads(response.text)
            for da in data['items']['item']:
                wr.writerow([y, '서울', gugun_map[g], da['occrrnc_cnt'],da['sido_sgg_nm'], da['caslt_cnt'], da['dth_dnv_cnt'], da['se_dnv_cnt'], da['sl_dnv_cnt'], da['wnd_dnv_cnt'],  da['lo_crd'], da['la_crd']])

f.close()

In [35]:
import pandas as pd

df = pd.read_csv('frequentzoneOldman.csv')

In [36]:
df

,year,sidocode,guguncode,occrrnc_cnt,caslt_cnt,dth_dnv_cnt,se_dnv_cnt,sl_dnv_cnt,wnd_dnv_cnt,lo_crd,la_crd
0,2015,서울,강남구,5,5,0,1,3,1,127.023858,37.507700
1,2015,서울,강남구,3,3,0,1,2,0,127.076399,37.492495
2,2015,서울,강동구,7,7,0,3,3,1,127.127708,37.537201
3,2015,서울,강동구,3,3,0,2,1,0,127.139970,37.537491
4,2015,서울,강북구,9,10,0,4,6,0,127.026477,37.625390
...,...,...,...,...,...,...,...,...,...,...,...
832,2021,서울,중구,5,5,1,4,0,0,126.962636,37.551737
833,2021,서울,중구,5,5,0,5,0,0,127.018699,37.565860
834,2021,서울,중랑구,5,6,1,4,1,0,127.054945,37.677949
835,2021,서울,중랑구,5,7,0,6,1,0,127.073646,37.659991
836,2021,서울,중랑구,5,5,0,5,0,0,127.080164,37.670290